### ISSUE TITLE
Stock Apps for Fire TV Cube 2nd gen

### ISSUE THREAD

**Issue by praspp** [Pro-me3us/raven_firmware#1]
Hi,
Could you publish links for Stock Apps Fire TV Cube 2nd gen.?
Thanks

**Comment by Pro-me3us** [comment]
I added a handful of stock apps to the bottom of the firmware page.  They are all from a few weeks ago, if you are looking for a specific app I can check for an update.  Most of the apps are not device specific.  Ighor has been keeping a [list of apps for the 4K Stick](https://gist.github.com/JulyIghor/d3d3dd460527a1d2b5b67954160d4abf) for a while, and he's more on top of that than me.

You can use the MD5 value from the Cube app to verify any specific app is the same between Cube and 4K Stick.

**Comment by praspp** [comment]
Thanks for the valuable information.
